### ISSUE TITLE
Parser Is Very Slow

### ISSUE THREAD

**Issue by chadSpeaksBootDev** [briot/tree-sitter-ada#10]
I'm wondering if anyone else has this experience or if I'm configuring it incorrectly. The highlighting causes many instances of input lag on keyboard strokes

**Comment by briot** [comment]
No problem on my side using neovim.  This project is not about the parser itself, just one grammar for it, so you might want to report upstream.   You did not provide a reproducer, so I am closing this issue.  Thanks
